/**
 * 
 */
package com.hellocld.AGED.basicComponents;

import java.util.HashMap;

import com.hellocld.AGED.core.Component;

/**
 * A rather complex component that works with the Collision2DSystem. It contains a list of objects
 * generated by the Collision2DSystem, each containing data relevant to different collisions that
 * occur during a single frame. 
 * @author CLD
 *
 */
public class Collision2D implements Component {
	public HashMap<CollideType, Float> collisionData = new HashMap<CollideType, Float>();
	public HashMap<Integer, HashMap<CollideType, Float>> collidingEntities = new HashMap<Integer, HashMap<CollideType, Float>>();
	//the enums for the HashMap of collision data
	public enum CollideType {
		CURRENT_X, CURRENT_Y, NEXT_X, NEXT_Y, HALFWIDTH, HALFHEIGHT, TIME, COLLISION_X, COLLISION_Y, OFFSET_X, OFFSET_Y
	}
	
	public Collision2D() {
		collisionData.put(CollideType.HALFWIDTH, 0.5f);
		collisionData.put(CollideType.HALFHEIGHT, 0.5f);
		collisionData.put(CollideType.OFFSET_X, 0f);
		collisionData.put(CollideType.OFFSET_X, 0f);
	}
	
	public void setSize(float w, float h) {
		collisionData.put(CollideType.HALFWIDTH, w/2);
		collisionData.put(CollideType.HALFHEIGHT, h/2);
	}
	
	public void setOffset(float x, float y) {
		collisionData.put(CollideType.OFFSET_X, x);
		collisionData.put(CollideType.OFFSET_Y, y);
	}
}
