/**
 * 
 */
package com.hellocld.AGED.basicComponents;

import java.util.HashMap;

import com.hellocld.AGED.core.Component;

/**
 * A rather complex component that works with the Collision2DSystem. It contains a list of objects
 * generated by the Collision2DSystem, each containing data relevant to different collisions that
 * occur during a single frame. 
 * @author CLD
 *
 */
public class Collision2D implements Component {
	
	//the enums for the HashMap of collision data
	public enum CollideType {
		X, Y, HW, HH, TIME
	}
	
	//the HashMap of this entities' collision data
	public HashMap<CollideType, Float> collisionData;
	
	//a HashMap of all the colliding entities and their data
	public HashMap<Integer, HashMap<CollideType, Float>> collidingEntities;
}
