/**
 * 
 */
package com.hellocld.AGED.basicComponents;

import com.hellocld.AGED.core.Component;

/**
 * A rather complex component that works with the Collision2DSystem. It contains a list of objects
 * generated by the Collision2DSystem, each containing data relevant to different collisions that
 * occur during a single frame. 
 * @author CLD
 *
 */
public class Collision implements Component {

}
